version: '3.1'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017

  mongo-init:
    image: mongo
    depends_on:
      - mongodb
    volumes:
      - ./init-db.sh:/init-db.sh
    entrypoint: ["/init-db.sh"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234